spring:
  application:
    name: weather-service
  datasource:
    url: jdbc:h2:mem:weather
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true

app:
  apikey:
    interval-ms: 3600000

open-weather:
  url: http://api.openweathermap.org/data/2.5/weather?q=%s,%s&appid=%s
  appid: 